apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  namespace: ardin
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  player.properties: |
   DB_HOSTNAME=db.hostname.
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    