apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: ardin
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432